### ISSUE TITLE
[BUG] Circuits "stick" when run on forest.qvm devices in tape mode

### ISSUE THREAD

**Issue by glassnotes** [PennyLaneAI/pennylane-forest#66] opened 2021-01-25 19:15 UTC
When running multiple QNodes in succession on the same device in tape mode, the first QNode gets executed during future runs.

Example:

```
import numpy as np
import pennylane as qml

qml.enable_tape()

dev0 = qml.device("forest.qvm", device="4q-qvm")

@qml.qnode(dev0)
def circuit0(params, x):
    qml.RX(x, wires=0)
    qml.Rot(*params, wires=2)

    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2))

params = np.array([1., 2., 3.])
x = 2.112

circuit0(params, x)
```
Result:
```
tensor([-0.506,  1.   , -0.48 ], requires_grad=True)
```

Create a new QNode and bind it to the same device:
```
@qml.qnode(dev0)
def circuit1():
    qml.CZ(wires=[1, 2])
    qml.CZ(wires=[1, 3])
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1)), qml.expval(qml.PauliZ(2))

circuit1()
```
gives result:
```
tensor([-0.482,  1.   , -0.418], requires_grad=False)
```

The results are the same (up to shot noise) as those of `circuit0`, while the true result should be `[1, 1, 1]` (in non-tape mode, this works fine).

**Comment by antalszava** [comment] 2021-01-26 23:22
This error is caused by having the same hash for every quantum tape (set to `0`).

The QVM has parametric compilation turned on by default. This means that it is checked if the circuit was executed already on the device. If yes, it will cache the compiled Forest program instead of executing it again. Caching happens based on the hash of the circuit, which in tape mode is a quantum tape (and the device is getting the same compiled program for every tape).

Resolving the issue will require a bit of thinking about how we'd like to update & create hashes for quantum tapes, so will further address it and link a PR (probably in PennyLane core).

**Comment by glassnotes** [comment] 2021-01-27 14:07
Thanks, @antalszava! I checked out the branch in [#1041](https://github.com/PennyLaneAI/pennylane/pull/1041), can confirm this fixes the issue so we can close this once that gets merged in :tada:

**Comment by antalszava** [comment] 2021-01-28 22:29
Closing with https://github.com/PennyLaneAI/pennylane/pull/1040 and https://github.com/PennyLaneAI/pennylane/pull/1041 merged.

**Closed by antalszava** 2021-01-28 22:29 UTC
Labels: bug
